version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auth:
    build: ./auth
    container_name: auth
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth
      - JWT_SECRET=topsecret
      - API_PORT=3000
    depends_on:
      - mongo

  locatarios:
    build: ./locatarios
    container_name: locatarios
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/locatarios
      - JWT_SECRET=topsecret
      - API_PORT=3001
    depends_on:
      - mongo

  pedidos:
    build: ./pedidos
    container_name: pedidos
    restart: always
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/pedidos
      - JWT_SECRET=topsecret
      - API_PORT=3002
    depends_on:
      - mongo

  pagos:
    build: ./pagos
    container_name: pagos
    restart: always
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/pagos
      - JWT_SECRET=topsecret
      - API_PORT=3003
    depends_on:
      - mongo

  reportes:
    build: ./reportes
    container_name: reportes
    restart: always
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=mongodb://mongo:27017/reportes
      - JWT_SECRET=topsecret
      - API_PORT=3004
    depends_on:
      - mongo

volumes:
  mongo_data: